name: Build & Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'  # Tự động chạy khi bạn push 1 Git tag như v1.0.0
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (optional)'
        required: false
        default: 'v1.0.0'
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # hoặc 7.0.x nếu bạn dùng net7

    - name: Get version from inputs or tag or fallback
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          v=${{ github.event.inputs.version }}
          v=${v#v}
          echo "version=$v" >> "$GITHUB_OUTPUT"
        elif [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
        else
          echo "version=0.0.0-preview" >> "$GITHUB_OUTPUT"
        fi

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build ToastifyWPF/ToastifyWPF.csproj -c Release

    - name: Pack with version from tag
      run: dotnet pack ToastifyWPF/ToastifyWPF.csproj -c Release -o ./nupkg /p:PackageVersion=${{ steps.version.outputs.version }} --no-build

    - name: Publish to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
